#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# ──────────────────────────────────────────────────────────────────────────
# Ebru AI — siteyi Oracle Cloud'a tasima sihirbazi.
#
# NE DEGISIYOR
#   Once : ebruai.com --Cloudflare tuneli--> ev bilgisayarindaki Flask
#          (bilgisayar kapaliyken site de kapali, 530 hatasi)
#   Sonra: ebruai.com --------------------> Oracle'daki Flask (7/24 acik)
#          ev bilgisayari yalnizca GORUNTU URETIYOR, istedigin zaman
#
# DEGISMEYEN
#   GPU, A1111, LoRA'lar ve uretim ayarlari ev bilgisayarinda kaliyor.
#   Mobil uygulama da etkilenmiyor: adres ebruai.com olarak kaliyor,
#   yeni APK gerekmiyor.
# ──────────────────────────────────────────────────────────────────────────

BETIK_DIZINI="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$BETIK_DIZINI/.env"

# Kaynak klasorler. Yerlesim degisirse buradan duzeltilir.
BACKEND_DIZINI="$BETIK_DIZINI"
WEB_DIZINI="$(cd "$BETIK_DIZINI/../../../Ebru_Web" 2>/dev/null && pwd || echo "")"
APK_YOLU="$WEB_DIZINI/static/indir/ebru-ai.apk"
DB_YOLU="$BACKEND_DIZINI/ebru.db"

ALAN_ADI="ebruai.com"

# ssh/scp'yi her cagirisi ayni ayarlarla yapmak icin.
ssh_calistir() {
  ssh -i "$SSH_ANAHTAR" \
      -o StrictHostKeyChecking=accept-new \
      -o ConnectTimeout=15 \
      "$SUNUCU_KULLANICI@$SUNUCU_IP" "$@"
}

banner "Ebru AI — Oracle Cloud kurulumu"

# ══════════════════════════════════════════════════════════════════════════
stage "Hazirlik ve SSH anahtari"
# ══════════════════════════════════════════════════════════════════════════
say "Once bu bilgisayarda gerekenleri kontrol edip sunucuya gireceginiz"
say "anahtari hazirliyorum. Bu asamada tarayici gerekmiyor."
printf '\n'

for arac in ssh scp tar curl; do
  if command -v "$arac" >/dev/null 2>&1; then
    note "  $arac bulundu"
  else
    warn "$arac bulunamadi — bu sihirbaz Git Bash icinde calistirilmali."
    exit 1
  fi
done

if [[ -z "$WEB_DIZINI" || ! -d "$WEB_DIZINI/templates" ]]; then
  warn "Site klasoru bulunamadi (aranan: $BETIK_DIZINI/../../../Ebru_Web)"
  ask WEB_DIZINI "Ebru_Web klasorunun tam yolu:"
  APK_YOLU="$WEB_DIZINI/static/indir/ebru-ai.apk"
fi
note "  site klasoru : $WEB_DIZINI"
note "  sunucu kodu  : $BACKEND_DIZINI"

SSH_ANAHTAR="$HOME/.ssh/ebru_oracle"
if [[ -f "$SSH_ANAHTAR" ]]; then
  printf '\n'
  note "SSH anahtari zaten var, yenisi uretilmedi."
else
  printf '\n'
  step "Sunucuya sifresiz girebilmek icin bir anahtar cifti uretiyorum."
  ssh-keygen -t ed25519 -f "$SSH_ANAHTAR" -N "" -C "ebru-oracle" >/dev/null
  note "uretildi: $SSH_ANAHTAR"
fi
write_env SSH_ANAHTAR "$SSH_ANAHTAR"

printf '\n'
say "${BOLD}Asagidaki satirin tamamini kopyala.${RESET} 3. asamada sunucuyu"
say "olustururken yapistiracaksin:"
printf '\n'
printf '%s\n' "$(cat "$SSH_ANAHTAR.pub")"
printf '\n'
pause "Kopyaladin mi? Enter"

# ══════════════════════════════════════════════════════════════════════════
stage "Oracle Cloud hesabi"
# ══════════════════════════════════════════════════════════════════════════
say "Oracle'in 'Always Free' katmani gercekten sureli degil: makine"
say "kapanmadigi surece ucretsiz kaliyor. Hesap acarken kart bilgisi"
say "isteniyor ama Always Free kaynaklarda ucret islemiyor."
printf '\n'
warn "Hesap acmayi ve kart dogrulamasini SEN yapmalisin; bu adim bana kapali."
printf '\n'

if confirm "Oracle hesabin zaten var mi?"; then
  note "iyi, dogrudan sunucu olusturmaya geciyoruz."
else
  open_url "https://signup.cloud.oracle.com/"
  step "Ulke ve ad bilgilerini gir."
  step "'Home Region' (ana bolge) sec — ${BOLD}sonradan degistirilemiyor${RESET}."
  note "  Turkiye'den en dusuk gecikme genelde Frankfurt ya da Amsterdam."
  step "Kart dogrulamasini tamamla ve e-postani onayla."
  printf '\n'
  note "Hesabin acilmasi bazen birkac dakika suruyor."
fi
pause "Hesap hazir oldugunda Enter"

# ══════════════════════════════════════════════════════════════════════════
stage "Sunucuyu olustur"
# ══════════════════════════════════════════════════════════════════════════
open_url "https://cloud.oracle.com/compute/instances"
say "Compute > Instances sayfasinda 'Create instance' de ve sunlari sec:"
printf '\n'
step "${BOLD}Image${RESET}: Canonical Ubuntu (24.04 ya da 22.04)."
step "${BOLD}Shape${RESET}: 'Change shape' > Ampere > ${BOLD}VM.Standard.A1.Flex${RESET}"
note "  Ucretsiz kota: 2 OCPU ve 12 GB. Ikisini de sonuna kadar ver."
note "  'Out of capacity' hatasi cikarsa: baska bir 'Availability domain'"
note "  dene, olmazsa VM.Standard.E2.1.Micro sec (1 GB bellek, yine ucretsiz)."
step "${BOLD}SSH keys${RESET}: 'Paste public keys' sec ve 1. asamadaki satiri yapistir."
step "'Create' de ve durumu 'Running' olana kadar bekle."
printf '\n'
say "Makine acildiginda sayfada 'Public IP address' yaziyor."
printf '\n'

ask SUNUCU_IP "Sunucunun genel IP adresi:"
write_env SUNUCU_IP "$SUNUCU_IP"

say "Ubuntu imajlarinda kullanici adi 'ubuntu', Oracle Linux'ta 'opc'."
ask SUNUCU_KULLANICI "Kullanici adi [ubuntu]:"
SUNUCU_KULLANICI="${SUNUCU_KULLANICI:-ubuntu}"
write_env SUNUCU_KULLANICI "$SUNUCU_KULLANICI"

# ══════════════════════════════════════════════════════════════════════════
stage "Ag kapilarini ac (VCN)"
# ══════════════════════════════════════════════════════════════════════════
say "Oracle'da ${BOLD}iki ayri${RESET} guvenlik duvari var ve ikisi de acilmadan"
say "site disaridan gorunmez:"
printf '\n'
note "  1) VCN guvenlik listesi  -> bu asamada, panelden (sen)"
note "  2) makinedeki iptables   -> 6. asamada, betik halleder (ben)"
printf '\n'
warn "Sadece birini acmak yetmez. 'Portu actim ama site acilmiyor' sikayetinin"
warn "sebebi neredeyse her zaman unutulan ikinci katmandir."
printf '\n'

open_url "https://cloud.oracle.com/networking/vcns"
step "VCN'ine gir > sol menuden 'Security Lists' > varsayilan listeyi ac."
step "'Add Ingress Rules' de ve ${BOLD}iki kural${RESET} ekle:"
note "     Source CIDR: 0.0.0.0/0   IP Protocol: TCP   Dest. Port: 80"
note "     Source CIDR: 0.0.0.0/0   IP Protocol: TCP   Dest. Port: 443"
printf '\n'
pause "Iki kural da eklendiyse Enter"

printf '\n'
say "Sunucuya baglanabiliyor muyum, bakalim..."
if ssh_calistir "echo baglandi" >/dev/null 2>&1; then
  printf '  %s✓%s SSH baglantisi calisiyor\n' "$GREEN" "$RESET"
else
  warn "Sunucuya baglanamadim."
  note "  - Makine 'Running' durumda mi?"
  note "  - IP dogru mu: $SUNUCU_IP"
  note "  - Anahtari olustururken yapistirdin mi?"
  note "  Elle denemek icin:"
  note "    ssh -i $SSH_ANAHTAR $SUNUCU_KULLANICI@$SUNUCU_IP"
  printf '\n'
  confirm "Yine de devam edeyim mi?" || exit 1
fi

# ══════════════════════════════════════════════════════════════════════════
stage "Kayit anahtari ve dosyalarin yuklenmesi"
# ══════════════════════════════════════════════════════════════════════════
say "Ev bilgisayari, uretimi actiginda kendini siteye tanitiyor. Bunu"
say "yaparken ortak bir gizli anahtar kullaniyor. Simdi onu uretip iki"
say "tarafa da yaziyorum."
printf '\n'

if [[ -n "$(_existing EBRU_REGISTER_TOKEN || true)" ]]; then
  EBRU_REGISTER_TOKEN="$(_existing EBRU_REGISTER_TOKEN)"
  note "Onceki calistirmadan kalan anahtar kullaniliyor."
else
  # Boru kullanilmiyor: "set -o pipefail" acikken "... | head -c 32"
  # ust taraftaki komutu SIGPIPE ile dusuruyor ve betik hata verip
  # kapaniyor. Asagidaki iki yol da tek komut.
  if command -v openssl >/dev/null 2>&1; then
    EBRU_REGISTER_TOKEN="$(openssl rand -hex 16)"
  else
    EBRU_REGISTER_TOKEN="$(python -c "import secrets; print(secrets.token_hex(16))")"
  fi
  note "Yeni anahtar uretildi."
fi
write_env EBRU_REGISTER_TOKEN "$EBRU_REGISTER_TOKEN"

# Ev bilgisayarindaki isci bu dosyadan okuyor. .bat oldugu icin
# CRLF ile yaziliyor; ayrica .gitignore'a adiyla eklenmis durumda.
AYAR_BAT="$BACKEND_DIZINI/uretim_ayarlar.bat"
{
  printf '@echo off\r\n'
  printf 'REM Uretim iscisinin ayarlari. oracle_kurulum.sh yazdi.\r\n'
  printf 'REM ICINDE GIZLI ANAHTAR VAR: depoya girmemeli.\r\n'
  printf 'set "EBRU_REGISTER_TOKEN=%s"\r\n' "$EBRU_REGISTER_TOKEN"
  printf 'set "EBRU_SITE_URL=https://%s"\r\n' "$ALAN_ADI"
} > "$AYAR_BAT"
printf '  %s✓ yazildi%s %s\n' "$GREEN" "$RESET" "$AYAR_BAT"

printf '\n'
say "Dosyalar yukleniyor..."
ssh_calistir "rm -rf ~/ebru_yukleme && mkdir -p ~/ebru_yukleme"

# venv (yuzlerce MB), gunlukler ve onbellek disarida birakiliyor.
note "  sunucu kodu"
tar -czf - \
    --exclude=venv --exclude=__pycache__ --exclude='*.pyc' \
    --exclude='*.log' --exclude='*.bak' --exclude='*.yedek_*' \
    --exclude='ebru.db' --exclude='.env' \
    --exclude='uretim_ayarlar.bat' \
    -C "$BACKEND_DIZINI" . \
  | ssh_calistir "mkdir -p ~/ebru_yukleme/server && tar -xzf - -C ~/ebru_yukleme/server"

# APK ayri gonderiliyor: 58 MB ve zaten sikistirilmis durumda.
note "  site sablonlari"
tar -czf - --exclude='./static/indir' --exclude='static/indir' --exclude=.vscode \
    -C "$WEB_DIZINI" . \
  | ssh_calistir "mkdir -p ~/ebru_yukleme/web && tar -xzf - -C ~/ebru_yukleme/web"

if [[ -f "$DB_YOLU" ]]; then
  note "  veritabani (hesaplar)"
  scp -i "$SSH_ANAHTAR" -o StrictHostKeyChecking=accept-new -q \
      "$DB_YOLU" "$SUNUCU_KULLANICI@$SUNUCU_IP:~/ebru_yukleme/ebru.db"
fi

if [[ -f "$APK_YOLU" ]]; then
  printf '\n'
  note "  APK — 58 MB, yukleme hizina gore birkac dakika surebilir"
  scp -i "$SSH_ANAHTAR" -o StrictHostKeyChecking=accept-new \
      "$APK_YOLU" "$SUNUCU_KULLANICI@$SUNUCU_IP:~/ebru_yukleme/ebru-ai.apk"
else
  warn "APK bulunamadi; /indir sayfasi 'henuz yuklenmedi' diyecek."
fi

printf '  %s✓%s dosyalar yuklendi\n' "$GREEN" "$RESET"

# ══════════════════════════════════════════════════════════════════════════
stage "Sunucu kurulumu"
# ══════════════════════════════════════════════════════════════════════════
say "Simdi sunucuda kurulum betigi calisacak. Yaptiklari:"
printf '\n'
note "  - iptables'ta 80/443 aciliyor (VCN'in ikinci katmani)"
note "  - Python, gunicorn ve Caddy kuruluyor"
note "  - site servis olarak tanimlaniyor, acilista kendiliginden kalkiyor"
note "  - HTTPS sertifikasi Caddy tarafindan otomatik aliniyor"
printf '\n'
note "Birkac dakika surer; cikti asagida akacak."
pause "Baslatmak icin Enter"
printf '\n'

if ssh_calistir "KAYIT_ANAHTARI='$EBRU_REGISTER_TOKEN' ALAN_ADI='$ALAN_ADI' bash ~/ebru_yukleme/server/sunucu_kur.sh"; then
  printf '\n  %s✓%s sunucu kurulumu tamamlandi\n' "$GREEN" "$RESET"
else
  printf '\n'
  warn "Kurulum yarida kaldi. Sunucudaki gunluge bakmak icin:"
  note "  ssh -i $SSH_ANAHTAR $SUNUCU_KULLANICI@$SUNUCU_IP"
  note "  sudo journalctl -u ebru.service -n 50 --no-pager"
  exit 1
fi

# ══════════════════════════════════════════════════════════════════════════
stage "ebruai.com'u Oracle'a cevir"
# ══════════════════════════════════════════════════════════════════════════
warn "Bu asama geri donusu zahmetli olan tek adim."
printf '\n'
say "Su an ebruai.com, Cloudflare tuneli uzerinden ev bilgisayarina"
say "gidiyor. Onu Oracle'a cevirecegiz. Bir sey ters giderse eski hale"
say "donmek icin A kayitlarini silip tuneli yeniden baglaman gerekir."
printf '\n'
confirm "Devam edeyim mi?" || { warn "Gecis yapilmadi. Sunucu hazir; istedigin zaman tekrar calistir."; exit 0; }

printf '\n'
open_url "https://dash.cloudflare.com/"
say "Cloudflare > ebruai.com > DNS bolumunde:"
printf '\n'
step "Tunelin olusturdugu ${BOLD}CNAME${RESET} kayitlarini sil (@ ve www)."
note "  Hedefleri ....cfargotunnel.com seklinde gorunur."
step "Iki ${BOLD}A${RESET} kaydi ekle:"
note "     Name: @      IPv4: $SUNUCU_IP     Proxy: ${BOLD}DNS only${RESET} (gri bulut)"
note "     Name: www    IPv4: $SUNUCU_IP     Proxy: ${BOLD}DNS only${RESET} (gri bulut)"
printf '\n'
warn "Simdilik GRI bulut. Caddy'nin sertifika alabilmesi icin ilk temasin"
warn "dogrudan sunucuya ulasmasi gerekiyor; turuncuyu sonraki asamada acacagiz."
printf '\n'
pause "Kayitlari duzenledin mi? Enter"

printf '\n'
say "Ev bilgisayarindaki kalici tunel artik gereksiz; ayni adrese iki"
say "yerden cevap gelmesin diye kapatalim."
step "${BOLD}Yonetici${RESET} PowerShell acip su komutu calistir:"
note "     Stop-Service Cloudflared; Set-Service Cloudflared -StartupType Manual"
printf '\n'
pause "Tunel servisini durdurdun mu? Enter"

printf '\n'
say "Sertifikanin gelmesi bekleniyor (Caddy kendisi aliyor)..."
BASARILI=0
for deneme in $(seq 1 20); do
  if curl -fsS -m 10 "https://$ALAN_ADI/health" >/dev/null 2>&1; then
    BASARILI=1
    break
  fi
  printf '  %s.%s' "$DIM" "$RESET"
  sleep 15
done
printf '\n'

if [[ "$BASARILI" -eq 1 ]]; then
  printf '  %s✓%s https://%s calisiyor\n' "$GREEN" "$RESET" "$ALAN_ADI"
else
  warn "5 dakikada cevap alinamadi. Muhtemel sebepler:"
  note "  - DNS degisikligi henuz yayilmadi (biraz daha bekle)"
  note "  - VCN kurallari ya da iptables eksik"
  note "  Sunucudan bakmak icin: sudo journalctl -u caddy -n 30 --no-pager"
  printf '\n'
  confirm "Yine de devam edeyim mi?" || exit 1
fi

# ══════════════════════════════════════════════════════════════════════════
stage "Cloudflare vekilini ac ve bitir"
# ══════════════════════════════════════════════════════════════════════════
say "Sertifika alindigina gore artik Cloudflare'i araya alabiliriz."
say "Bu, sunucunun IP adresini gizler ve onunde bir koruma katmani olur."
printf '\n'
open_url "https://dash.cloudflare.com/"
step "DNS bolumunde iki A kaydini da ${BOLD}Proxied${RESET} (turuncu bulut) yap."
step "SSL/TLS > Overview'da kipi ${BOLD}Full (strict)${RESET} sec."
note "  'Flexible' secme: Cloudflare ile sunucu arasi sifresiz kalir."
printf '\n'
pause "Ikisini de yaptin mi? Enter"

printf '\n'
say "Son kontrol..."
sleep 5
if curl -fsS -m 15 "https://$ALAN_ADI/health" 2>/dev/null | grep -q '"status"'; then
  printf '  %s✓%s site ayakta\n' "$GREEN" "$RESET"
  curl -fsS -m 15 "https://$ALAN_ADI/health" 2>/dev/null | head -c 300
  printf '\n'
  printf '\n'
  note "'ready: false' ve 'uretim kapali' gormen NORMAL — su an ev"
  note "bilgisayarinda uretim iscisi calismiyor. Zaten istenen bu:"
  note "site ayakta, uretim kapali."
else
  warn "Site su an cevap vermiyor. Vekil ayari yayilana kadar birkac"
  warn "dakika surebilir; biraz sonra tekrar dene."
fi

printf '\n'
say "${BOLD}Bundan sonra uretimi nasil aciyorsun:${RESET}"
printf '\n'
step "Acmak icin : $BACKEND_DIZINI/uretim_baslat.bat"
note "     A1111'i baslatir, tuneli acar, siteye haber verir."
step "Kapatmak icin: o pencereyi kapat."
note "     Site ayakta kalir, yalnizca uretim kapanir."
printf '\n'
note "Artik sunucu_baslat.bat'a ihtiyacin yok: Flask ve kalici tunel"
note "sunucuya tasindi."

finish
